
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 11 09:13:08 CEST 2017
//----------------------------------------------------

package rs.ac.bg.etf.ma120261d_pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 23;
  public static final int CHAR = 45;
  public static final int CONST = 18;
  public static final int GE = 32;
  public static final int LBRCK = 14;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int FOR = 21;
  public static final int MINUS = 25;
  public static final int STATIC = 24;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int LS = 33;
  public static final int OR = 36;
  public static final int BOOL = 46;
  public static final int COMMA = 8;
  public static final int CLASS = 17;
  public static final int INC = 42;
  public static final int DIV = 40;
  public static final int EXT = 22;
  public static final int PLUS = 11;
  public static final int IF = 49;
  public static final int DOT = 44;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RBRCK = 15;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int ADD = 37;
  public static final int NUMBER = 47;
  public static final int MOD = 28;
  public static final int IDENT = 48;
  public static final int BREAK = 16;
  public static final int VOID = 13;
  public static final int SPLIT = 27;
  public static final int EQ = 29;
  public static final int TIMES = 26;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int READ = 20;
  public static final int REMND = 41;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int NE = 30;
  public static final int DEC = 43;
  public static final int GT = 31;
  public static final int SUB = 38;
  public static final int PRINT = 9;
}

